name: multi-docker

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./client
          file: ./client/Dockerfile.dev
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/react-test

      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./client
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/multi-client


      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./nginx
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/multi-nginx


      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./server
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/multi-server

      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./worker
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/multi-worker